version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce-admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network

  backend:
    image: ecommerce-backend
    container_name: ecommerce_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: ecommerce-admin
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
